version: '3.4'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433" 
    healthcheck:
        test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Pass@word" -Q "SELECT 1" || exit 1
        interval: 10s
        timeout: 3s
        retries: 10
        start_period: 10s
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - https_port=7443
      - Kestrel__Certificates__Default__Path=./certs/devcert.pfx
      - Kestrel__Certificates__Default__Password=Passw@rd
      - Sql__ConnectionString=${Users_DB:-Server=sql;Database=HexSampleDb;User Id=sa;Password=Pass@word; TrustServerCertificate=True}
    ports:
      - "6080:80"
      - "6443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
    - sql
